import Head from "next/head";
import styles from "../styles/Home.module.css";
import { RandomSVG } from "../components/randomSvg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Random Blob</h1>
        <div className={styles.svgWrapper}>
          <RandomSVG />
        </div>
      </main>
    </div>
  );
}
